<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <PackageId>CromulentBisgetti.ContainerPacking.Services</PackageId>
    <Version>10.0.1.4</Version>
    <Authors>joakimja</Authors>
    <Company></Company>
    <Description>3D container packing library forked from David M. Chapman’s 3DContainerPacking project under MIT License.</Description>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageProjectUrl>https://github.com/joakimja/3DContainerPacking</PackageProjectUrl>
    <RepositoryUrl>https://github.com/joakimja/3DContainerPacking</RepositoryUrl>
    <RepositoryType>git</RepositoryType>

    <!-- Licensing info -->
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>© 2025 joakimja. Based on work by David M. Chapman under MIT License.</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Update="README.md" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
